matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8']
      env:
        - CXX=g++-8
    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0']
          packages: ['clang-6.0']
      env:
        - CXX=clang++-6.0

before_script:
  - mkdir build
  - cd build
  - cmake ..

env:
  - CXX=clang++-6.0 

script: make && make ink-cpp-test && ./ink-cpp-test --use-colour no