language: cpp
sudo: false
dist: trusty
compiler:
- g++
os:
- linux

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - lcov

before_script:
- mkdir build
- cd build
- cmake ..
script: make && make ink-cpp-test && ./ink-cpp-test --use-colour no

env:
  - CXX=g++-9